### ISSUE TITLE
TODO: Future updates to the website.

### ISSUE THREAD

**Issue by Explosion-Scratch** [Explosion-Scratch/scratchaddons.github.io#3]
Stuff we need to do:
- [x] Make text more readable, maybe in columns or have wider margins.
- [x] Custom 404 page.
- [x] Port all pages to the new themed website.
- [x] Figure out how to resize an iframe without cropping it.
- [x] Take some of @Hans5958's ideas for the front page into account.

**Comment by YOYITsM3M8** [comment]
> Stuff we(me) need to do:
xD

**Comment by YOYITsM3M8** [comment]
I'll do contributors

**Comment by Explosion-Scratch** [comment]
> I'll do contributors
> **edit**: and contribute

Thanks! :)

**Comment by YOYITsM3M8** [comment]
np

**Comment by WorldLanguages** [comment]
> Addon documentation.

No, that will stay on the wiki.

**Comment by YOYITsM3M8** [comment]
how about a link to the wiki

**Comment by WorldLanguages** [comment]
That's fine.

**Comment by YOYITsM3M8** [comment]
k

**Comment by Explosion-Scratch** [comment]
> > Addon documentation.
> 
> No, that will stay on the wiki.



> how about a link to the wiki

Okay!

**Comment by Explosion-Scratch** [comment]
The only thing we need now is the sticky header.

**Comment by YOYITsM3M8** [comment]
and link to wiki

**Comment by Explosion-Scratch** [comment]
All done for now! :)

**Comment by Explosion-Scratch** [comment]
I'll start on some wiki docs.

**Comment by Explosion-Scratch** [comment]
I'm going to re-open this and pin it, and update it frequently with stuff that still needs to be done.

**Comment by GrahamSH-LLK** [comment]
I'll contribute!

**Comment by Hans5958** [comment]
Here's a prototype from mine: https://codepen.io/Hans5958/full/WNwdRwa

**Comment by GrahamSH-LLK** [comment]
> Here's a prototype from me: https://codepen.io/Hans5958/full/WNwdRwa

We already do have a website at scratchaddons.github.io. Take a look! (Although that mockup does look amazing!)

**Comment by Hans5958** [comment]
> 
> 
> > Here's a prototype from me: [codepen.io/Hans5958/full/WNwdRwa](https://codepen.io/Hans5958/full/WNwdRwa)
> 
> We already do have a website at scratchaddons.github.io. Take a look! (Although that mockup does look amazing!)

I am already aware for that. I even have discussed in on the Discord server. I made this just in case it needs a makeover.

Including that folder structure

**Comment by Explosion-Scratch** [comment]
I'm already working on a makeover here:
https://scratchaddonsrestyle.explosionscratc.repl.co It has dark theme,
lots of interactive stuff, it took me forever to make lol. Today I'll work
on converting the rest of the the site to that.

On Monday, September 7, 2020, Hans5958 <notifications@github.com> wrote:
> Here's a prototype from me: codepen.io/Hans5958/full/WNwdRwa
>
> We already do have a website at scratchaddons.github.io. Take a look!
(Although that mockup does look amazing!)
>
> I am already aware for that. I even have discussed in on the Discord
server. I made this just in case it needs a makeover.
>
> Including that folder structure
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/t5pCWbYGeavqSe2n7uamS1g6A_s_ACsvUvIluw9afg_hIrMOgfbq34vjvOQJtg0A9xW-sEfJ6uaQZ3MLH8gE2qfvyUHfhD9tWVlJcUDe4yDoPUMr-fwKhitZ5eztQrDv84OkXe2cv7DcvoZDWxkdD4LlqSwrEwgANm_s3IkOpFf65b7uYa-zsgPUUK4H5JM9tbxlXbuaaT0OFNR9vahc47NJjAP_n_H9KKFLluOs2g=s0-d-e1-ft#https://github.com/notifications/beacon/AOT2P3VEXIQJPYUQHYSRZH3SES3G5A5CNFSM4QYV2ZHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFEC4RFY.gif>

**Comment by Explosion-Scratch** [comment]
Also Hans5958, your mockup is great, I'll see what I can to to put that
into the main website.

On Monday, September 7, 2020, Thomas Stafford <explosion.scratch@gmail.com>
wrote:
> I'm already working on a makeover here:
https://scratchaddonsrestyle.explosionscratc.repl.co It has dark theme,
lots of interactive stuff, it took me forever to make lol. Today I'll work
on converting the rest of the the site to that.
>
> On Monday, September 7, 2020, Hans5958 <notifications@github.com> wrote:
>> Here's a prototype from me: codepen.io/Hans5958/full/WNwdRwa
>>
>> We already do have a website at scratchaddons.github.io. Take a look!
(Although that mockup does look amazing!)
>>
>> I am already aware for that. I even have discussed in on the Discord
server. I made this just in case it needs a makeover.
>>
>> Including that folder structure
>>
>> —
>> You are receiving this because you modified the open/close state.
>> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/t5pCWbYGeavqSe2n7uamS1g6A_s_ACsvUvIluw9afg_hIrMOgfbq34vjvOQJtg0A9xW-sEfJ6uaQZ3MLH8gE2qfvyUHfhD9tWVlJcUDe4yDoPUMr-fwKhitZ5eztQrDv84OkXe2cv7DcvoZDWxkdD4LlqSwrEwgANm_s3IkOpFf65b7uYa-zsgPUUK4H5JM9tbxlXbuaaT0OFNR9vahc47NJjAP_n_H9KKFLluOs2g=s0-d-e1-ft#https://github.com/notifications/beacon/AOT2P3VEXIQJPYUQHYSRZH3SES3G5A5CNFSM4QYV2ZHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFEC4RFY.gif>

**Comment by Hans5958** [comment]
Oh darn your email response thing

**Comment by Explosion-Scratch** [comment]
Oof lol

**Comment by Daniel4-Scratch** [comment]
Note: Website is hosted at https://explosion-scratch.github.io/scratchaddons.github.io/ not scratchaddons.github.io

**Comment by GrahamSH-LLK** [comment]
> Note: Website is hosted at https://explosion-scratch.github.io/scratchaddons.github.io/ not scratchaddons.github.io

That's because @WorldLanguages chose to use a different website design. It will eventually be at scratchaddons.com.
